version: "3.8"
services:
  app:
    image: filebrowser/filebrowser
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - $PWD/database.db:/database.db
      - $PWD/filebrowser.json:/.filebrowser.json
      - app_data:/srv
    networks:
      proxy_apps:
    labels:
      backups: "true"

volumes:
  app_data:

networks:
  proxy_apps:
    name: proxy_apps
    external: true
