version: "3.8"
services:
  app:
    image: filebrowser/filebrowser
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - db_data:/database
      - app_data:/srv
    networks:
      proxy_apps:
    labels:
      backups: "true"

volumes:
  db_data:
  app_data:

networks:
  proxy_apps:
    name: proxy_apps
    external: true
